/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'apple' at '19/01/17 20:05' with Gradle 2.14.1
 *
 * @author apple, @date 19/01/17 20:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
